title: Onkel Tom
name: Onkel Tom
description: "Modern, minimal personal site"
url: https://onkeltom.github.io
baseurl: ""
permalink: /:categories/:title/
timezone: Europe/Berlin
markdown: kramdown
collections:
  recipes:
    output: true
    permalink: /recipes/:name/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe
      is_recipe: true
sass:
  sass_dir: assets/css
  style: compressed
